---
ansible_python_interpreter: python3

ip_whitelist:
  - "1.1.1.1"
ip_whitelist_ssh:
  - "1.1.1.2"
azure_location: eastus
base_name: DetectionLab0
base_rg: DetectionLab0ansible
base_vm_size: Standard_D1_v2
#base_managedisk: 'Standard_LRS'
base_adminuser_login: "{{ base_name }}admin"
# must match Azure password requirements: lowercase, uppercase, digit, special chars (3 on 4), 12-123 chars
base_adminuser_password: Password_1234_to_change!
base_adminuser_sshkeyfile: "/path/to/.ssh/id_rsa.pub"
base_adminuser_sshkeyfile_priv: "/path/to/.ssh/id_rsa"
base_adminuser_sshkey: "{{ lookup('file', base_adminuser_sshkeyfile) }}"
wef_user: "{{ base_adminuser_login }}"
wef_userpass: "{{ base_adminuser_password }}"
win_join_domain_user: "windomain.local\\{{ base_adminuser_login }}"
win_join_domain_pass: "{{ base_adminuser_password }}"
base_vn: "192.168.0.0/16"
base_subnet: "192.168.38.0/24"
base_nsg_rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist_ssh }}"
      - name: Splunk
        protocol: Tcp
        destination_port_range: 8000
        access: Allow
        priority: 1002
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist }}"
      - name: Fleet
        protocol: Tcp
        destination_port_range: 8412
        access: Allow
        priority: 1003
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist }}"
      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1004
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist }}"
      - name: WinRM-http
        protocol: Tcp
        destination_port_range: 5985
        access: Allow
        priority: 1005
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist }}"
      - name: WinRM-https
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1006
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist }}"
      - name: WinATA
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 1007
        direction: Inbound
        source_address_prefix: "{{ ip_whitelist }}"
      # Allow all traffic from the private subnet
      - name: PrivateSubnet
        protocol: Tcp
        destination_port_range: "*"
        access: Allow
        priority: 1010
        direction: Inbound
        source_address_prefix: "192.168.38.0/24"

detectionlab_win_reboot: true
detectionlab_stats: false
detectionlab_online: true
detectionlab_azurebastion: true
wef_atalight_target_enable: false

kolide_enrollment_secret: enrollmentsecret
win_osquery_fleetserver: kolide
win_osquery_secret: "{{ kolide_enrollment_secret }}"
win_osquery_secret_path: 'C:\Program Files\osquery\certs\enroll_secret.txt'
# push certificate from orchestrator
win_osquery_cert_push: true
win_osquery_cert_orchestrator_path: 'fleet.crt'
win_osquery_cert_path: 'C:\Program Files\osquery\certs\fleet.crt'
