---

- name: Ensure latest packages
  package:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Ensure git is present
  package:
    name: git
    state: present
  become: yes

- name: Set hostname
  hostname:
    name: logger

# stupid raw porting from Vagrant for now
- name: Configure logger host
  shell: "{{ item }}"
  become: yes
  args:
    creates: /opt/DetectionLab/Vagrant/bootstrap.log
  with_items:
    - "adduser --disabled-password --gecos \"\" vagrant && echo 'vagrant:vagrant' | chpasswd"
    - "mkdir /home/vagrant/.ssh && cp /home/{{ base_adminuser_login }}/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys && chown -R vagrant:vagrant /home/vagrant/.ssh"
    - "echo 'vagrant    ALL=(ALL:ALL) NOPASSWD:ALL' | tee -a /etc/sudoers"
    - "git clone https://github.com/clong/DetectionLab.git /opt/DetectionLab"
    - "sed -i 's/eth1/eth0/g' /opt/DetectionLab/Vagrant/bootstrap.sh"
    - "sed -i 's/ETH1/ETH0/g' /opt/DetectionLab/Vagrant/bootstrap.sh"
    - "sed -i 's#/usr/local/go/bin/go get -u#GOPATH=/root/go /usr/local/go/bin/go get -u#g' /opt/DetectionLab/Vagrant/bootstrap.sh"
    - "sed -i 's#/vagrant/resources#/opt/DetectionLab/Vagrant/resources#g' /opt/DetectionLab/Vagrant/bootstrap.sh"
    - "chmod +x /opt/DetectionLab/Vagrant/bootstrap.sh"
    - "apt-get -qq update"
    - "/opt/DetectionLab/Vagrant/bootstrap.sh 2>&1 | tee /opt/DetectionLab/Vagrant/bootstrap.log"
  ignore_errors: true
